### ISSUE TITLE
make with monsters

### ISSUE THREAD

**Issue by Derpolino** [fewfre/DeadMazeDressroom#1]
http://transformice.com/images/x_deadmeat/x_monstres/x_monstre_1.swf
there are :
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31

**Comment by fewfre** [comment]
Nice find! I guess I could try and setup a bestiary of sorts. I'll probably put it off until I finish this, and rewrite the other two dressrooms I made with my improvements from this (unless you wish to have a bestiary sooner than later).

Sorry for late reply, had a long extended weekend away.

**Comment by Derpolino** [comment]
No problem ;)

**Comment by fewfre** [comment]
Alright, nothing to fancy, but I made a little gallery where you can preview the monsters and their poses. enjoy!

https://github.com/fewfre/DeadMazeBestiary

**Comment by Derpolino** [comment]
Nice :p
